### ISSUE TITLE
Github Action fails with v0.22.0

### ISSUE THREAD

**Issue by jlec** [pappasam/toml-sort#34]
When running github action pre-commit hook I get

```
Pretty format TOML............................................................Failed
- hook id: pretty-format-toml
- exit code: 1
Input File pyproject.toml is not a valid TOML file: TomlSort.__init__() got an unexpected keyword argument 'only_sort_tables'
```

This is the GH action

```
      - uses: pre-commit/action@v3.0.0
        env:
          # yamllint disable-line rule:line-length
          SKIP: detect-aws-credentials,protect-first-parent,terraform_docs,terraform_providers_lock,terraform_tflint,terraform_tfsec,terraform_checkov,terrascan
```
