### ISSUE TITLE
Option to prevent deletion of orphan comments

### ISSUE THREAD

**Issue by maresb** [pappasam/toml-sort#59]
Hi, in the context of [pretty-format-toml](https://github.com/macisamuele/language-formatters-pre-commit-hooks) I was recently surprised by the disappearance of a multi-paragraph comment. After investigation I discovered that it was interpreted by toml-sort as an orphan comment.

For example,
```toml
# paragraph 1

# paragraph 2
[a-section]
```
and then `# paragraph 1` vanishes.

I ended up solving this with

```toml
# paragraph 1
#
# paragraph 2
[a-section]
```

Would it make sense to add an option which changes the behavior so that orphan comments are added to the next section rather than deleted?

**Comment by brodybits** [comment]
Likely related:

```toml
[a-section]
# this comment is preserved
config1 = 123

# this orphaned part all gone
# config2 = 456
```

**Comment by brodybits** [comment]
My apologies for the incorrect example, just tested this example:

```toml
[a-section]
# this comment is preserved
config1 = 123

# this orphaned part is removed
# config2 = 456

[b-section]
config3=789

# seems to be preserved at the end:
# config4=901
```

**Comment by mpounsett** [comment]
I was just writing a different feature request, but I think this comes closer to solving my problem.  I have a suggestion that I think solves both our problems.

Here's what I'm thinking:

`--comment-paragraphs` (or something like that, if someone has a better idea) adds tracking of empty lines between comments, and only ends a comment block when a new section or EOF is encountered.  

This solves my problem where Alembic's `pyproject` template adds a `[tool.alembic]` section to the bottom of the file, and also a raft of comments that include suggested configuration sections.  Because the comments are in paragraphs, this winds up with huge sections of comments being deleted by toml-sort, and the very last block of comments being left orphaned at the bottom of the file, separated from the main alembic section which gets sorted up higher.

Treating whitespace between comments as "connecting" two comments in the same block would fix this problem.   Trailing empty lines could still be removed.

In order to continue to support comments connected to a following section when they're not separated by whitespace, when a new section is encountered, scan backward through the collected comments for the first empty line and break the comment block there.  The top half goes with the previous section, the bottom half with the new section.

```toml
[section-a]
# Section A comment paragraph 1

# Section A comment paragraph 2

# Section B comment
[section-b]
```

Based on about 5 minutes of scanning the sort code I think this is implementable, but it does add some complexity.  I have an idea how it might be approached, but I'd need to test a bunch (assuming @pappasam doesn't want to tackle it themselves).  I assume I'm missing some nuance in my first browse of the code. :)

**Comment by mpounsett** [comment]
Hmm.. it looks like the behaviour I'd expect doesn't even work.  Comments after the last key in a section get disconnected from that section in all cases.  The very last comment block in the file remains sorted at the bottom of the file, and (as noted above) all other comments are deleted.

I would really expect this to work, currently:

```toml
[a-section]
# a-section comment 1
option = true
# a -section comment 2
a_list = []
# a-section comment 3
# in a long paragraph
# possibly containing
# [a-section.subsection]
# tempoarrily_disabled = ''
# options = true

[b-section]
```

However, the fact that the comment 3 block is always deleted makes toml-sort useless to me as-is.  I'd really like to see something like my suggestion above implemented (and I'm willing to put work into it myself).
