### ISSUE TITLE
How to exclude/skip a file (e.g. `poetry.lock`)?

### ISSUE THREAD

**Issue by jamesbraza** [pappasam/toml-sort#65]
I am using `toml-sort==0.23.1` with the below `pyproject.toml` config:

```toml
[tool.tomlsort]
all = true
in_place = true
trailing_comma_inline_array = true
```

I integrate `toml-sort` into my `pre-commit` like so:

```yaml
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
```

Running [`identify`](https://github.com/pre-commit/identify) to see the associations on `poetry.lock`:

```bash
> identify-cli poetry.lock
["file", "non-executable", "text", "toml"]
```

We can see it's considered TOML, so `toml-sort` will pick it up.  However, `poetry.lock` is made programmatically, so it should not be touched by `toml-sort`.

How can one skip a particular file?  I don't see anything in `toml-sort --help` that will exclude or skip files.

Is the only route right now to use an `exclude` within `pre-commit`?

**Comment by vfazio** [comment]
i think you would use either the `files` or `exclude` option within pre-commit

```
  - repo: https://github.com/pappasam/toml-sort/
    rev: v0.23.1
    hooks:
      - id: toml-sort
        name: Sort pyproject.toml
        entry: toml-sort
        files: pyproject.toml
        args: []
```

```
  - repo: https://github.com/pappasam/toml-sort/
    rev: v0.23.1
    hooks:
      - id: toml-sort
        name: Sort pyproject.toml
        entry: toml-sort
        exclude: poetry.lock
        args: []
```
