### ISSUE TITLE
Bug: toml-sort moves and entries to different groups

### ISSUE THREAD

**Issue by 15r10nk** [pappasam/toml-sort#67]
This bug was reported here https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/198, but it is actually a bug in toml-sort.

The minimal reproducible toml file for this error is 

``` toml
[x]
v.w = ""

[x.r]
```

which gets formatted to:

``` toml
[x]

[x.r]
v.w = ""
```
