### ISSUE TITLE
Handle shortcut for nested property

### ISSUE THREAD

**Issue by 0x26res** [pappasam/toml-sort#71]
For context, I have a `libs.versions.toml` file to express the versions of my library in gradle, it looks a bit like this (full example [here](https://docs.gradle.org/current/userguide/platforms.html)

```toml
[versions]
groovy = "3.0.5"
checkstyle = "8.37"

[libraries]
groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
groovy-nio = { module = "org.codehaus.groovy:groovy-nio", version.ref = "groovy" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = { strictly = "[3.8, 4.0[", prefer="3.9" } }
```

It's using a short cut, `version.ref = "groovy"`, instead of `version = {ref = "groovy"}`. This confuses `toml-sort`.

 ```toml
[libraries]
groovy-core = {module = "org.codehaus.groovy:groovy", version. = ref = "groovy"}
groovy-json = {module = "org.codehaus.groovy:groovy-json", version. = ref = "groovy"}
groovy-nio = {module = "org.codehaus.groovy:groovy-nio", version. = ref = "groovy"}
commons-lang3 = {group = "org.apache.commons", name = "commons-lang3", version = {strictly = "[3.8, 4.0[", prefer = "3.9"}}

[versions]
groovy = "3.0.5"
checkstyle = "8.37"
```
